version: '3.1'
services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    command: "mongod --config /etc/mongod.conf"
    restart: always
