version: '3.1'
services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: adm1n
      ENV MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/fixtures/:/docker-entrypoint-initdb.d/
    command: "mongod --bind_ip_all --config /etc/mongod.conf"
    restart: always
